# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
#
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
#
# Discord: https://discord.gg/papermc
# IRC: #paper @ irc.esper.net ( https://webchat.esper.net/?channels=paper )
# Website: https://papermc.io/
# Docs: https://paper.readthedocs.org/

use-display-name-in-quit-message: false
verbose: false
config-version: 20
settings:
  fix-entity-position-desync: true
  track-plugin-scoreboards: false
  max-joins-per-tick: 3
  console-has-all-permissions: false
  chunk-tasks-per-tick: 1000
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  enable-player-collisions: true
  load-permissions-yml-before-plugins: true
  bungee-online-mode: true
  save-player-data: true
  queue-light-updates-max-loss: 10
  incoming-packet-spam-threshold: 300
  region-file-cache-size: 256
  sleep-between-chunk-saves: false
  use-versioned-world: false
  save-empty-scoreboard-teams: false
  suggest-player-names-when-null-tab-completions: true
  use-alternative-luck-formula: true
  async-chunks:
    enable: true
    threads: -1
  spam-limiter:
    recipe-spam-increment: 1
    recipe-spam-limit: 20
    tab-spam-increment: 1
    tab-spam-limit: 500
  velocity-support:
    enabled: false
    online-mode: false
    secret: ""
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  watchdog:
    early-warning-every: 50000
    early-warning-delay: 100000
  unsupported-settings:
    allow-headless-pistons: false
    allow-permanent-block-break-exploits: false
    allow-piston-duplication: false
    allow-permanent-block-break-exploits-readme: This setting controls if players
      should be able to break bedrock, end portals and other intended to be permanent
      blocks.
    allow-piston-duplication-readme: This setting controls if player should be able
      to use TNT duplication, but this also allows duplicating carpet, rails and potentially
      other items
    allow-headless-pistons-readme: This setting controls if players should be able
      to create headless pistons.
  console:
    enable-brigadier-highlighting: true
    enable-brigadier-completions: true
  item-validation:
    display-name: 8192
    loc-name: 8192
    lore-line: 8192
    book:
      title: 8192
      author: 8192
      page: 16384
timings:
  server-name: Vibe Sesh
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
    - database
    - settings.bungeecord-addresses
    - settings.velocity-support.secret
  history-interval: 300
  history-length: 3600
messages:
  no-permission: "&cI'm sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error."
  kick:
    connection-throttle: You were kicked for attemping to join too many times. Please
      wait.
    flying-player: You were kicked for Fly or a similar exploit
    flying-vehicle: You were kicked for Fly or a similar exploit
    authentication-servers-down: The Minecraft servers appear to be down
world-settings:
  default:
    seed-based-feature-search-loads-chunks: true
    fix-items-merging-through-walls: false
    map-item-frame-cursor-limit: 128
    only-players-collide: false
    allow-vehicle-collisions: true
    portal-search-vanilla-dimension-scaling: true
    fix-climbing-bypassing-cramming-rule: false
    max-leash-distance: 10.0
    fix-wither-targeting-bug: false
    ender-dragons-death-always-places-dragon-egg: false
    allow-using-signs-inside-spawn-protection: false
    update-pathfinding-on-block-update: true
    should-remove-dragon: false
    zombies-target-turtle-eggs: true
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    light-queue-size: 20
    tracker-update-distance: 1.0
    iron-golems-can-spawn-in-air: false
    zombie-villager-infection-chance: -1.0
    seed-based-feature-search: true
    portal-create-radius: 16
    fix-zero-tick-instant-grow-farms: true
    entities-target-with-follow-range: false
    per-player-mob-spawns: true
    all-chunks-are-slime-chunks: false
    armor-stands-do-collision-entity-lookups: true
    keep-spawn-loaded-range: 8
    auto-save-interval: -1
    skip-entity-ticking-in-chunks-scheduled-for-unload: true
    keep-spawn-loaded: true
    disable-ice-and-snow: false
    skeleton-horse-thunder-spawn-chance: 0.01
    disable-thunder: false
    use-faster-eigencraft-redstone: true
    grass-spread-tick-rate: 4
    bed-search-radius: 1
    container-update-tick-rate: 3
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    prevent-tnt-from-moving-in-water: false
    non-player-arrow-despawn-rate: 60
    creative-arrow-despawn-rate: 60
    allow-non-player-entities-on-scoreboards: false
    nether-ceiling-void-damage-height: 0
    water-over-lava-flow-speed: 5
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    remove-corrupt-tile-entities: true
    experience-merge-max-value: -1
    spawner-nerfed-mobs-should-jump: false
    mob-spawner-tick-rate: 2
    armor-stands-tick: false
    baby-zombie-movement-speed: 0.5
    disable-teleportation-suffocation-check: false
    allow-leashing-undead-horse: false
    optimize-explosions: true
    save-queue-limit-for-auto-save: 50
    max-auto-save-chunks-per-tick: 6
    max-chunk-gens-per-tick: 10
    use-vanilla-world-scoreboard-name-coloring: false
    max-chunk-sends-per-tick: 81
    queue-light-updates: false
    fixed-chunk-inhabited-time: -1
    fire-physics-event-for-redstone: false
    delay-chunk-unloads-by: 10s
    prevent-moving-into-unloaded-chunks: true
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
    portal-search-radius: 128
    count-all-mobs-for-spawning: false
    filter-nbt-data-from-spawn-eggs-and-related: true
    disable-creeper-lingering-effect: false
    max-entity-collisions: 2
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    anti-xray:
      use-permission: false
      lava-obscures: false
      enabled: true
      engine-mode: 1
      chunk-edge-mode: 2
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
        - gold_ore
        - iron_ore
        - coal_ore
        - lapis_ore
        - mossy_cobblestone
        - obsidian
        - chest
        - diamond_ore
        - redstone_ore
        - clay
        - emerald_ore
        - ender_chest
      replacement-blocks:
        - stone
        - oak_planks
    squid-spawn-height:
      maximum: 0.0
    game-mechanics:
      disable-mob-spawner-spawn-egg-transformation: false
      fix-curing-zombie-villager-discount-exploit: true
      nerf-pigmen-from-nether-portals: false
      disable-pillager-patrols: false
      disable-relative-projectile-velocity: false
      disable-chest-cat-detection: true
      disable-sprint-interruption-on-attack: false
      disable-end-credits: true
      disable-player-crits: false
      shield-blocking-delay: 5
      disable-unloaded-chunk-enderpearl-exploit: true
      scan-for-legacy-ender-dragon: false
      villages-load-chunks: false
      pillager-patrols:
        spawn-chance: 0.2
        spawn-delay:
          per-player: false
          ticks: 12000
        start:
          per-player: false
          day: 5
    despawn-ranges:
      soft: 28
      hard: 96
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    max-growth-height:
      cactus: 3
      reeds: 3
      bamboo:
        max: 16
        min: 11
    lightning-strike-distance-limit:
      sound: -1
      impact-sound: -1
      flash: -1
    lootables:
      auto-replenish: true
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    hopper:
      cooldown-when-full: true
      disable-move-event: true
    alt-item-despawn-rate:
      enabled: true
      items:
        COBBLESTONE: 300
        NETHERRACK: 300
    generator-settings:
      flat-bedrock: false
    baby-zombie-movement-modifier: 0.5
    viewdistances:
      no-tick-view-distance: 12
    entity-per-chunk-save-limit:
      experience_orb: -1
      snowball: -1
      ender_pearl: -1
      arrow: -1
    door-breaking-difficulty:
      zombie:
        - HARD
      vindicator:
        - NORMAL
        - HARD
    mobs-can-always-pick-up-loot:
      zombies: false
      skeletons: false
    wandering-trader:
      spawn-minute-length: 1200
      spawn-day-length: 24000
      spawn-chance-failure-increment: 25
      spawn-chance-min: 25
      spawn-chance-max: 75
    unsupported-settings:
      fix-invulnerable-end-crystal-exploit: true
    spawn-limits:
      monsters: -1
      animals: -1
      water-animals: -1
      water-ambient: -1
      ambient: -1
  survival_nether:
    keep-spawn-loaded: false
  survival_the_end:
    keep-spawn-loaded: false
