# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# For a reference for any variable inside this file, check out the Spigot wiki at
# http://www.spigotmc.org/wiki/spigot-configuration/
# 
# If you need help with the configuration or have any questions related to Spigot,
# join us at the IRC or drop by our forums and leave a post.
# 
# IRC: #spigot @ irc.spi.gt ( http://www.spigotmc.org/pages/irc/ )
# Forums: http://www.spigotmc.org/

config-version: 12
settings:
  log-villager-deaths: true
  restart-script: ./start.sh
  debug: false
  save-user-cache-on-stop-only: false
  sample-count: 12
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  bungeecord: false
  timeout-time: 60
  restart-on-crash: false
  netty-threads: 4
  user-cache-size: 1000
  player-shuffle: 0
  late-bind: false
  attribute:
    maxHealth:
      max: 100000000
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: That is not a valid command.
  server-full: The server has too many players online for you to join. Please contact
    the owner.
  outdated-client: Your client is too old. Please use version {0}
  outdated-server: Your client is too new. Please use version {0}
  restart: The server is restarting. Please wait a moment.
stats:
  disable-saving: false
  forced-stats: {}
advancements:
  disable-saving: false
  disabled:
  - minecraft:story/disabled
commands:
  silent-commandblock-console: false
  spam-exclusions:
  - /skill
  log: true
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
  tab-complete: 0
  send-namespaced: true
world-settings:
  default:
    seed-bastion: 30084232
    seed-fortress: 30084232
    seed-mansion: 10387319
    seed-fossil: 14357921
    seed-portal: 34222645
    end-portal-sound-radius: 0
    seed-endcity: 10387313
    trident-despawn-rate: 300
    view-distance: default
    seed-outpost: 165745296
    verbose: true
    item-despawn-rate: 6000
    enable-zombie-pigmen-portal-spawns: true
    wither-spawn-sound-radius: 0
    arrow-despawn-rate: 300
    mob-spawn-range: 6
    max-tnt-per-tick: 100
    hopper-amount: 1
    random-light-updates: false
    zombie-aggressive-towards-villager: true
    nerf-spawner-mobs: false
    hanging-tick-frequency: 100
    seed-village: 10387312
    seed-desert: 14357617
    seed-igloo: 14357618
    seed-jungle: 14357619
    seed-swamp: 14357620
    seed-monument: 10387313
    seed-shipwreck: 165745295
    seed-ocean: 14357621
    seed-slime: 987234911
    dragon-death-sound-radius: 0
    max-entity-collisions: 8
    merge-radius:
      item: 4.0
      exp: 6.0
    growth:
      bamboo-modifier: 100
      sweetberry-modifier: 100
      kelp-modifier: 100
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      beetroot-modifier: 100
      carrot-modifier: 100
      potato-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
      vine-modifier: 100
      cocoa-modifier: 100
    max-tick-time:
      tile: 1000
      entity: 1000
    squid-spawn-range:
      min: 45.0
    entity-activation-range:
      villagers-work-immunity-after: 100
      villagers-work-immunity-for: 20
      villagers-active-for-panic: true
      villagers: 32
      flying-monsters: 32
      raiders: 48
      animals: 16
      monsters: 24
      misc: 8
      water: 12
      tick-inactive-villagers: false
      wake-up-inactive:
        animals-max-per-tick: 4
        animals-every: 1200
        animals-for: 100
        monsters-max-per-tick: 8
        monsters-every: 400
        monsters-for: 100
        villagers-max-per-tick: 4
        villagers-every: 300
        villagers-for: 100
        flying-monsters-max-per-tick: 8
        flying-monsters-every: 200
        flying-monsters-for: 100
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hunger:
      jump-walk-exhaustion: 0.05
      jump-sprint-exhaustion: 0.2
      combat-exhaustion: 0.1
      regen-exhaustion: 6.0
      swim-multiplier: 0.01
      sprint-multiplier: 0.1
      other-multiplier: 0.0
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
  worldeditregentempworld:
    verbose: false
players:
  disable-saving: false
